import { useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, Wallet } from '@phosphor-icons/react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { cycleTotals, goalSaved, money, shortDate, type Entry } from './lib/data'
import { expenseTypes, transferTypes } from './lib/labels'
import { Empty, IconBadge, Metric, Progress, SectionHead } from './ui'

const palette = ['#2d7356', '#8bae91', '#b49860', '#b77969', '#768279', '#c4ccaa']
type ReportTab = 'overview' | 'trends' | 'rules'

export default function ReportsView({ all, paydays, transactions }: { all: Entry[]; paydays: Entry[]; transactions: Entry[] }) {
  const [tab, setTab] = useState<ReportTab>('overview')
  const [goalsKind, setGoalsKind] = useState<'wish' | 'goal'>('wish')
  const spent = transactions.filter((item) => expenseTypes.includes(item.transactionType || ''))
  const income = transactions.filter((item) => item.transactionType === 'income').reduce((sum, item) => sum + (item.amount || 0), 0)
  const expenses = spent.reduce((sum, item) => sum + (item.amount || 0), 0)
  const transfers = transactions.filter((item) => transferTypes.includes(item.transactionType || '')).reduce((sum, item) => sum + (item.amount || 0), 0)
  const categories = Object.entries(spent.reduce<Record<string, number>>((result, item) => { const key = item.category || 'Other'; result[key] = (result[key] || 0) + (item.amount || 0); return result }, {})).sort((a, b) => b[1] - a[1]).map(([name, value]) => ({ name, value }))
  const cycles = [...paydays].reverse().map((item) => { const totals = cycleTotals(all, item); return { name: item.date ? shortDate(item.date) : item.name, Income: totals.income, Expenses: totals.expenses, Remaining: totals.remaining } })
  const goals = all.filter((item) => item.kind === goalsKind)
  const rules = all.filter((item) => item.kind === 'rule')

  return <section className="page-section reports-page">
    <div className="page-intro reports-intro"><div><p className="eyebrow">THE BIGGER PICTURE</p><h2>Reports & auto rules</h2><p>Follow spending, paydays, and the goals they support.</p></div></div>
    <div className="tab-list report-tabs" role="tablist" aria-label="Report sections">{(['overview', 'trends', 'rules'] as ReportTab[]).map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? 'tab active' : 'tab'} onClick={() => setTab(item)}>{item === 'rules' ? 'Auto rules' : item[0].toUpperCase() + item.slice(1)}</button>)}</div>
    {tab === 'overview' && <div className="report-overview tab-content">
      <div className="report-metrics"><Metric label="Total income" value={money(income)} tone="teal" icon={ArrowDownLeft} /><Metric label="Total spent" value={money(expenses)} tone="coral" icon={ArrowUpRight} /><Metric label="After actual outflows" value={money(income - expenses - transfers)} tone="blue" icon={Wallet} /></div>
      <div className="report-chart-grid"><section className="panel chart-panel spending-chart"><SectionHead title="Spending by category" />{categories.length ? <div className="donut-layout"><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius="62%" outerRadius="86%" startAngle={90} endAngle={-270} paddingAngle={2}>{categories.map((item, index) => <Cell key={item.name} fill={palette[index % palette.length]} />)}</Pie><Tooltip formatter={(value) => money(Number(value))} /></PieChart></ResponsiveContainer><div className="donut-center"><strong>{money(expenses)}</strong><small>Total spent</small></div></div><div className="legend">{categories.map((item, index) => <div key={item.name}><i style={{ background: palette[index % palette.length] }} /><span>{item.name}</span><strong>{money(item.value)} <small>({Math.round(item.value / expenses * 100)}%)</small></strong></div>)}</div></div> : <Empty title="No spending to report" body="Expense transactions will appear here." />}</section>
      <section className="panel chart-panel income-chart"><SectionHead title="Income vs. expenses" />{cycles.length ? <div className="bar-box"><ResponsiveContainer width="100%" height="100%"><BarChart data={cycles} barGap={3}><CartesianGrid stroke="#e1e8df" vertical={false} /><XAxis dataKey="name" stroke="#708475" tickLine={false} axisLine={false} tick={{ fontSize: 10 }} /><YAxis stroke="#708475" tickLine={false} axisLine={false} tickFormatter={(value: number) => `${Math.round(value / 1000)}k`} tick={{ fontSize: 10 }} width={31} /><Tooltip formatter={(value) => money(Number(value))} /><Bar dataKey="Income" fill="#286c50" radius={[3, 3, 0, 0]} /><Bar dataKey="Expenses" fill="#b1c3a2" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div> : <Empty title="Add a payday" body="Payday comparisons will appear here." />}<div className="chart-legend"><span><i style={{ background: '#286c50' }} />Income</span><span><i style={{ background: '#b1c3a2' }} />Expenses</span></div></section></div>
      <section className="panel report-goals"><div className="goal-switch" role="tablist" aria-label="Goal type"><button role="tab" aria-selected={goalsKind === 'goal'} className={goalsKind === 'goal' ? 'active' : ''} onClick={() => setGoalsKind('goal')}>Savings goals</button><button role="tab" aria-selected={goalsKind === 'wish'} className={goalsKind === 'wish' ? 'active' : ''} onClick={() => setGoalsKind('wish')}>Wishlist</button></div><SectionHead title={goalsKind === 'wish' ? 'Planned purchases' : 'Savings goals'} />{goals.length ? goals.map((item) => <div className="report-goal-row" key={item.id}><IconBadge kind={item.kind} /><div><strong>{item.name}</strong><small>{money(goalSaved(all, item))} / {money(item.target)}{item.targetDate ? ` · ${shortDate(item.targetDate)}` : ''}</small><Progress current={goalSaved(all, item)} target={item.target || 0} /></div><span className={`priority-tag ${item.priority?.toLowerCase() || ''}`}>{item.priority || 'Goal'}</span></div>) : <Empty title="No goals yet" body="Goals you add in Planning will appear here." />}</section>
    </div>}
    {tab === 'trends' && <div className="tab-content report-detail-grid"><section className="panel"><SectionHead title="Payday trend" />{cycles.length ? cycles.map((item) => <div className="trend-row" key={item.name}><strong>{item.name}</strong><span>Income {money(item.Income)}</span><span>Expenses {money(item.Expenses)}</span><b>{money(item.Remaining)} left</b></div>) : <Empty title="No paydays yet" body="Add a payday to compare cycles." />}</section><section className="panel"><SectionHead title="Category breakdown" />{categories.length ? categories.map((item, index) => <div className="category-row" key={item.name}><i style={{ background: palette[index % palette.length] }} /><span>{item.name}</span><strong>{money(item.value)}</strong><small>{Math.round(item.value / expenses * 100)}%</small></div>) : <Empty title="No categories yet" body="Recorded spending will appear here." />}</section></div>}
    {tab === 'rules' && <section className="panel tab-content"><SectionHead title="Automatic allocations" /><p className="muted">These rules reserve part of a payday budget. Payments are recorded separately.</p>{rules.length ? rules.map((item) => <div className="rule-report-row" key={item.id}><IconBadge kind="rule" /><span><strong>{item.name}</strong><small>{item.ruleMode?.replace('_', ' ') || 'Manual'}</small></span><b>{item.ruleMode?.includes('percent') ? `${item.ruleValue || 0}%` : money(item.ruleValue)}</b></div>) : <Empty title="No auto rules yet" body="Add a rule in Planning to see it here." />}</section>}
  </section>
}
