import { Plus, PencilSimple } from '@phosphor-icons/react'
import { cycleTotals, goalSaved, money, shortDate, type Entry, type Kind } from './lib/data'
import { Empty, IconBadge, Progress, Row, SectionHead } from './ui'
import { txLabels } from './lib/labels'
import AccountsView from './AccountsView'
import BillsSchedule from './BillsSchedule'

export type PlanningTab = 'paydays' | 'bills' | 'accounts' | 'wishlist' | 'savings' | 'rules'
export type OpenForm = (kind: Kind, entry?: Entry, preset?: Partial<Entry>) => void
interface CommonProps { all: Entry[]; open: OpenForm }

// Older sample databases predate the artwork marker. Match only the original sample row.
function demoArtwork(item: Entry) {
  return item.artwork === 'double-deck' || (item.kind === 'wish' && item.name === 'Double deck' && item.target === 15000 && item.saved === 3000 && item.targetDate === '2026-12-31')
    ? '/images/double-deck.png'
    : undefined
}

export { default as HomeView } from './HomeOverview'

export function ActivityView({ all, open, transactions, cycle }: CommonProps & { transactions: Entry[]; cycle?: Entry }) {
  const plans = all.filter((item) => item.kind === 'plan')
  return <section className="page-section"><div className="page-intro"><div><p className="eyebrow">YOUR LEDGER</p><h2>Every move, accounted for.</h2><p>Actual spending is separate from what you plan to spend.</p></div><button className="primary-button" onClick={() => open('transaction')}><Plus size={18} /> Add entry</button></div><div className="activity-layout"><section className="panel"><SectionHead title="Transactions" />{transactions.length ? transactions.map((item) => <Row key={item.id} item={item} detail={`${item.date ? shortDate(item.date) : ''} · ${txLabels[item.transactionType || 'expense']}${item.category ? ` · ${item.category}` : ''}`} aside={`${item.transactionType === 'income' ? '+' : '−'}${money(item.amount)}`} onClick={() => open('transaction', item)} />) : <Empty title="No transactions yet" body="Record income or an expense to begin your history." action="Add entry" onAction={() => open('transaction')} />}</section><section className="panel"><SectionHead title="Planned expenses" action="Add plan" onAction={() => open('plan', undefined, { paydayId: cycle?.id })} />{plans.length ? plans.map((item) => { const spent = transactions.filter((tx) => tx.transactionType === 'expense' && tx.category === item.category && tx.paydayId === item.paydayId).reduce((sum, tx) => sum + (tx.amount || 0), 0); return <div className="planned-row" key={item.id}><Row item={item} aside={money(item.budget)} detail={item.category || 'Planned'} onClick={() => open('plan', item)} /><div className="planned-foot">Spent {money(spent)} <span>{money((item.budget || 0) - spent)} left</span></div><Progress current={spent} target={item.budget || 0} /></div> }) : <Empty title="Plan before you spend" body="Set a category budget for a payday and compare it with actual expenses." action="Add plan" onAction={() => open('plan', undefined, { paydayId: cycle?.id })} />}</section></div></section>
}

function GoalPanel({ kind, all, items, open, cycle }: CommonProps & { kind: 'wish' | 'goal'; items: Entry[]; cycle?: Entry }) {
  return <section className="panel goal-panel"><SectionHead title={kind === 'wish' ? 'Desires to buy' : 'Savings goals'} action={kind === 'wish' ? 'Add wish' : 'Add goal'} onAction={() => open(kind)} /><p className="muted">{kind === 'wish' ? 'Keep planned purchases separate from actual expenses.' : 'Build a reserve for the future, one contribution at a time.'}</p><div className="goal-grid">{items.map((item) => { const saved = goalSaved(all, item); const artwork = demoArtwork(item); return <div className={`goal-card ${artwork ? 'has-artwork' : ''}`} key={item.id}>{artwork && <img className="goal-card-image" src={artwork} alt="Wooden double-deck bed" loading="lazy" />}<div className="goal-card-top">{!artwork && <IconBadge kind={kind} />}<button aria-label={`Edit ${item.name}`} onClick={() => open(kind, item)}><PencilSimple size={16} /></button></div><strong>{item.name}</strong><small>{item.priority || (item.targetDate ? `Target ${shortDate(item.targetDate)}` : 'Your goal')}</small><div className="goal-amount"><strong>{money(saved)}</strong><span>/ {money(item.target)}</span></div><Progress current={saved} target={item.target || 0} /><button className="subtle-button" onClick={() => open('transaction', undefined, { name: `${item.name} contribution`, transactionType: kind === 'wish' ? 'wish_contribution' : 'goal_deposit', accountId: item.id, paydayId: cycle?.id, category: kind === 'wish' ? 'Wishlist' : 'Savings' })}><Plus size={15} /> Add contribution</button></div> })}</div>{!items.length && <Empty title={kind === 'wish' ? 'Your wishlist starts here' : 'No savings goals yet'} body="Give a goal a name and target amount to follow your progress." action={kind === 'wish' ? 'Add wish' : 'Add goal'} onAction={() => open(kind)} />}</section>
}

export function PlanningView({ all, open, tab, setTab, cycle, paydays, onToggleReminder }: CommonProps & { tab: PlanningTab; setTab: (tab: PlanningTab) => void; cycle?: Entry; paydays: Entry[]; onToggleReminder: (item: Entry, enabled: boolean) => void }) {
  const totals = cycle ? cycleTotals(all, cycle) : null
  return <section className="page-section"><div className="page-intro planning-intro"><div><p className="eyebrow">LOOKING AHEAD</p><h2>A place for what comes next.</h2><p>Paydays, commitments and bigger goals, all together.</p></div></div><div className="tab-list" role="tablist" aria-label="Planning sections">{(['paydays', 'bills', 'accounts', 'wishlist', 'savings', 'rules'] as PlanningTab[]).map((item) => <button role="tab" aria-selected={tab === item} className={tab === item ? 'tab active' : 'tab'} key={item} onClick={() => setTab(item)}>{item === 'paydays' ? 'Paydays' : item === 'bills' ? 'Bills' : item === 'accounts' ? 'Loans & cards' : item === 'wishlist' ? 'Wishlist' : item === 'savings' ? 'Savings' : 'Auto rules'}</button>)}</div><div className="tab-content" key={tab}>
    {tab === 'paydays' && <div className="planning-grid"><section className="panel"><SectionHead title="Payday cycles" action="Add payday" onAction={() => open('payday')} />{paydays.length ? paydays.map((item) => { const sum = cycleTotals(all, item); return <button className="cycle-card" key={item.id} onClick={() => open('payday', item)}><div><IconBadge kind="payday" /><span><strong>{shortDate(item.date)}</strong><small>{item.name}</small></span></div><strong>{money(sum.remaining)}</strong><div className="cycle-card-foot"><span>Income {money(sum.income)}</span><span>Expenses {money(sum.expenses)}</span></div></button> }) : <Empty title="No paydays yet" body="Add your first payday cycle." action="Add payday" onAction={() => open('payday')} />}</section><section className="panel"><SectionHead title="How rules apply" />{cycle ? <><p className="muted">On {shortDate(cycle.date)}, rules reserve money before it becomes available to spend. A matching payment reduces the reserved amount.</p>{totals?.allocations.map((item) => <div className="breakdown-line" key={item.id}><span>{item.name}</span><strong>{money(item.reserved)} reserved</strong></div>)}<div className="summary-line"><span>Available after rules</span><strong>{money(totals?.available)}</strong></div></> : <Empty title="Ready when you are" body="Add a payday to see your budget breakdown." />}</section></div>}
    {tab === 'bills' && <BillsSchedule all={all} open={open} cycle={cycle} onToggleReminder={onToggleReminder} />}
    {tab === 'accounts' && <AccountsView all={all} open={open} cycle={cycle} onWishlist={() => setTab('wishlist')} />}
    {tab === 'wishlist' && <GoalPanel kind="wish" all={all} items={all.filter((item) => item.kind === 'wish')} open={open} cycle={cycle} />}
    {tab === 'savings' && <GoalPanel kind="goal" all={all} items={all.filter((item) => item.kind === 'goal')} open={open} cycle={cycle} />}
    {tab === 'rules' && <section className="panel"><SectionHead title="Automatic allocations" action="Add rule" onAction={() => open('rule')} /><p className="muted">Rules reserve budget; they do not create a payment. Add a transaction when money actually moves.</p>{all.filter((item) => item.kind === 'rule').map((item) => <Row key={item.id} item={item} detail={item.ruleMode?.replace('_', ' ') || 'Manual'} aside={item.ruleMode?.includes('percent') ? `${item.ruleValue || 0}%` : money(item.ruleValue)} onClick={() => open('rule', item)} />)}{!all.some((item) => item.kind === 'rule') && <Empty title="No rules yet" body="Automate tithes, savings or fixed set-asides." action="Add rule" onAction={() => open('rule')} />}</section>}
  </div></section>
}
